plugin_source_files = [
  "fluid_sim.cpp",
]

other_source_files = [
  "libs/loguru/loguru.cpp",
  "src/error_util.cpp",
  "src/file_util.cpp",
  "src/sort.cpp",
  "src/thread_pool.cpp",
  "src/descriptor_management.cpp",
]

[[procedures]]
name = "setParams"
args = [
  { type = "SimData*" },
  { type = "const SimParameters*" },
]
return = "void"

[[procedures]]
name = "create"
args = [
  { type = "const SimParameters*" },
  { type = "const VulkanContext*" },
  { type = "u32fast", name = "particle_count" },
  { type = "const vec4*", name = "p_initial_positions" },
]
return = "SimData"

[[procedures]]
name = "destroy"
args = [
  { type = "SimData*" },
  { type = "const VulkanContext*" },
]
return = "void"

[[procedures]]
name = "advance"
args = [
  { type = "SimData*" },
  { type = "const VulkanContext*" },
  { type = "f32", name = "delta_t" },
  { type = "VkSemaphore", name = "optional_wait_semaphore" },
  { type = "VkSemaphore", name = "optional_signal_semaphore" },
]
return = "void"

[[procedures]]
name = "getPositionsVertexBuffer"
args = [
  { type = "const SimData*" },
  { type = "VkBuffer*", name = "buffer_out" },
  { type = "VkDeviceSize*", name = "buffer_size_out" },
]
return = "void"

