plugin_source_files = [
  "fluid_sim.cpp",
]

other_source_files = [
  "libs/loguru/loguru.cpp",
  "src/error_util.cpp",
  "src/file_util.cpp",
]

[[procedures]]
name = "setParams"
args = [
  { type = "SimData*" },
  { type = "const SimParameters*" },
]
return = "void"

[[procedures]]
name = "create"
args = [
  { type = "const SimParameters*" },
  { type = "const VulkanContext*" },
  { type = "u32fast", name = "particle_count" },
  { type = "const vec3*", name = "p_initial_positions" },
]
return = "SimData"

[[procedures]]
name = "destroy"
args = [
  { type = "SimData*" },
]
return = "void"

[[procedures]]
name = "advance"
args = [
  { type = "SimData*" },
  { type = "const VulkanContext*" },
  { type = "f32", name = "delta_t" },
]
return = "void"

